### ISSUE TITLE
Wrong arguments Exception 

### ISSUE THREAD

**Issue by indapublic** [btd/node-detect-encoding#1]
Trying to run example on my source string

``` javascript
var detectEncoding = require("detect-encoding");

            var buffer = row.PERS_NAME;
            var charset = detectEncoding(buffer, function (err, result) {
                console.log(result);
            });
```

And receiving exception

> ```
>       var charset = detectEncoding(buffer, function (err, result) {
>                     ^
> TypeError: Wrong arguments
> ```

**Comment by btd** [comment]
It just means your buffer variable, is not really Buffer.

**Comment by indapublic** [comment]
Hm. Ok, thank you very much
