### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by mike-aungsan** [btd/node-detect-encoding#3]
I remove only debian wheezy host name from the log.
###### 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/detect-encoding
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "detect-encoding"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! detect-encoding@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detect-encoding@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the detect-encoding package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls detect-encoding
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

46 silly install resolved     description: 'Simple binding for ICU charset detector',
46 silly install resolved     keywords: [ 'encoding-detection', 'icu' ],
46 silly install resolved     repository:
46 silly install resolved      { type: 'git',
46 silly install resolved        path: 'git://github.com/btd/node-detect-encoding.git' },
46 silly install resolved     homepage: 'http://github.com/btd/node-detect-encoding',
46 silly install resolved     bugs: { url: 'http://github.com/btd/node-detect-encoding/issues' },
46 silly install resolved     author: { name: 'Denis Bardadym', email: 'bardadymchik@gmail.com' },
46 silly install resolved     licenses: [ [Object] ],
46 silly install resolved     scripts: { install: 'node-gyp rebuild' },
46 silly install resolved     gypfile: true,
46 silly install resolved     _id: 'detect-encoding@0.0.3',
46 silly install resolved     dist:
46 silly install resolved      { shasum: 'efe9ff7b99765425576d2fb965ce91069e333bd7',
46 silly install resolved        tarball: 'http://registry.npmjs.org/detect-encoding/-/detect-encoding-0.0.3.tgz' },
46 silly install resolved     _from: 'detect-encoding@*',
46 silly install resolved     _npmVersion: '1.4.3',
46 silly install resolved     _npmUser: { name: 'btd', email: 'bardadymchik@gmail.com' },
46 silly install resolved     maintainers: [ [Object] ],
46 silly install resolved     directories: {},
46 silly install resolved     _shasum: 'efe9ff7b99765425576d2fb965ce91069e333bd7',
46 silly install resolved     _resolved: 'https://registry.npmjs.org/detect-encoding/-/detect-encoding-0.0.3.tgz' } ]
47 info install detect-encoding@0.0.3 into /home/
48 info installOne detect-encoding@0.0.3
49 verbose installOne of detect-encoding to /home/ not in flight; installing
50 verbose lock using /root/.npm/_locks/detect-encoding-58e662ff237120b2.lock for /home/node_modules/detect-encoding
51 silly install write writing detect-encoding 0.0.3 to /home/node_modules/detect-encoding
52 silly cache addNamed cb detect-encoding@0.0.3
53 verbose unbuild node_modules/detect-encoding
54 silly gentlyRm /home/node_modules/detect-encoding is being purged from base /home/
55 verbose gentlyRm don't care about contents; nuking /home/node_modules/detect-encoding
56 verbose tar unpack /root/.npm/detect-encoding/0.0.3/package.tgz
57 verbose tar unpacking to /home/node_modules/detect-encoding
58 silly gentlyRm /home/node_modules/detect-encoding is being purged
59 verbose gentlyRm don't care about contents; nuking /home/node_modules/detect-encoding
60 silly gunzTarPerm modes [ '755', '644' ]
61 silly gunzTarPerm extractEntry package.json
62 silly gunzTarPerm extractEntry .npmignore
63 silly gunzTarPerm extractEntry README.md
64 silly gunzTarPerm extractEntry LICENSE
65 silly gunzTarPerm extractEntry detect-encoding.js
66 silly gunzTarPerm extractEntry binding.gyp
67 silly gunzTarPerm extractEntry detect-encoding.cpp
68 info preinstall detect-encoding@0.0.3
69 silly install resolved []
70 verbose about to build /home/node_modules/detect-encoding
71 info build /home/node_modules/detect-encoding
72 verbose linkStuff [ false, false, false, '/home/node_modules' ]
73 info linkStuff detect-encoding@0.0.3
74 verbose linkBins detect-encoding@0.0.3
75 verbose linkMans detect-encoding@0.0.3
76 verbose rebuildBundles detect-encoding@0.0.3
77 info install detect-encoding@0.0.3
78 verbose unsafe-perm in lifecycle false
79 info detect-encoding@0.0.3 Failed to exec install script
80 verbose unlock done using /root/.npm/_locks/detect-encoding-58e662ff237120b2.lock for /home/node_modules/detect-encoding
81 verbose stack Error: detect-encoding@0.0.3 install: `node-gyp rebuild`
81 verbose stack Exit status 1
81 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
81 verbose stack     at EventEmitter.emit (events.js:110:17)
81 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
81 verbose stack     at ChildProcess.emit (events.js:110:17)
81 verbose stack     at maybeClose (child_process.js:1015:16)
81 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
82 verbose pkgid detect-encoding@0.0.3
83 verbose cwd /home/
84 error Linux 3.2.0-4-amd64
85 error argv "/usr/bin/node" "/usr/bin/npm" "install" "detect-encoding"
86 error node v0.12.2
87 error npm  v2.7.4
88 error code ELIFECYCLE
89 error detect-encoding@0.0.3 install: `node-gyp rebuild`
89 error Exit status 1
90 error Failed at the detect-encoding@0.0.3 install script 'node-gyp rebuild'.
90 error This is most likely a problem with the detect-encoding package,
90 error not with npm itself.
90 error Tell the author that this fails on your system:
90 error     node-gyp rebuild
90 error You can get their info via:
90 error     npm owner ls detect-encoding
90 error There is likely additional logging output above.
91 verbose exit [ 1, true ]
92 verbose unbuild node_modules/detect-encoding
93 info preuninstall detect-encoding@0.0.3
94 info uninstall detect-encoding@0.0.3
95 verbose unbuild rmStuff detect-encoding@0.0.3 from /home/node_modules
96 info postuninstall detect-encoding@0.0.3
97 silly gentlyRm /home/node_modules/detect-encoding is being purged from base /home/
98 verbose gentlyRm don't care about contents; nuking /home/node_modules/detect-encoding
99 silly vacuum-fs purging /home/node_modules/detect-encoding
100 silly vacuum-fs quitting because other entries in /home/node_modules

**Comment by btd** [comment]
Hello.
I do not support this module anymore. For more robust solution try [this module](https://www.npmjs.com/package/charset-detector). It is ported icu charset detector to javascript.
