### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by shubham399** [btd/node-detect-encoding#5]
$npm install detect-encoding
> detect-encoding@0.0.3 install /home/user/Work/Projects/project/node_modules/detect-encoding
> node-gyp rebuild

make: Entering directory '/home/user/Work/Projects/project/node_modules/detect-encoding/build'
  CXX(target) Release/obj.target/detect_encoding/detect-encoding.o
../detect-encoding.cpp:13:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../detect-encoding.cpp:26:24: error: variable or field ‘DetectWork’ declared void
 static void DetectWork(uv_work_t* req) {
                        ^
../detect-encoding.cpp:26:24: error: ‘uv_work_t’ was not declared in this scope
../detect-encoding.cpp:26:35: error: ‘req’ was not declared in this scope
 static void DetectWork(uv_work_t* req) {
                                   ^
detect_encoding.target.mk:93: recipe for target 'Release/obj.target/detect_encoding/detect-encoding.o' failed
make: *** [Release/obj.target/detect_encoding/detect-encoding.o] Error 1
make: Leaving directory '/home/user/Work/Projects/project/node_modules/detect-encoding/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-53-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Work/Projects/project/node_modules/detect-encoding
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN project@1.0.0 No description
npm WARN The package chai is included as both a dev and production dependency.
npm WARN The package mocha is included as both a dev and production dependency.
npm WARN The package supertest is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detect-encoding@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detect-encoding@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-08-21T08_47_04_743Z-debug.log

$ echo $PATH
/home/user/bin:/home/user/.local/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin/icu-config

OS: Linx Mint 18.2
$ node -v
v8.4.0
$ npm -v
5.3.0

$node-gyp rebuild
module.js:491
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by btd** [comment]
I do not support this module. Use `charset-detector` it is js port of ICU charset detector.
